name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Python 3.8
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3.8 python3.8-venv python3.8-dev
    
    - name: Set up Python 3.8 virtual environment
      run: |
        python3.8 -m venv venv
        source venv/bin/activate
        python --version
        pip install --upgrade pip
    
    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest -v